const products = [
	{
		_id: "1",
		name: "Unicorn Fuffly Chair",
		image: "/images/unicorn-fuffly-chair.jpg",
		description:
			"Children's Study Desk Chair, Sweat Seats Kids Colorful Chair Cute Animal Computer Rolling Swivel Chair with White Foot",
		brand: "Guyou Store",
		category: "Furniture",
		price: 119.99,
		countInStock: 10,
		rating: 4.5,
		numReviews: 12,
	},
	{
		_id: "2",
		name: "Fluffly Unicorn",
		image: "/images/fuffly-unicorn.jpg",
		description: "Despicable Me 2 Agnes Fluffy Unicorn stuffed toy",
		brand: "Receesoon",
		category: "Toy",
		price: 14.99,
		countInStock: 7,
		rating: 4.0,
		numReviews: 8,
	},
	{
		_id: "3",
		name: "Unicorn Fluffly-Fluff Bagpack",
		image: "/images/unicorn-fuffly-fuff-gagpack.jpg",
		description:
			"Start the school year off right with the perfectf fluffy backpack! Featuring a rainbow design of pastel colours and sequins with a sparkly unicorn horn and ears, carry all your classroom essentials in this magical backpack.",
		brand: "Claire's",
		category: "Stationery",
		price: 79.99,
		countInStock: 5,
		rating: 3,
		numReviews: 12,
	},
	{
		_id: "4",
		name: "Unicorn Fluffly Towel",
		image: "/images/unicorn-fuffly-towel.jpg",
		description:
			"Use this towel at the beach, in your bathroom or the office and have a unicorn with you everywhere",
		brand: "Amazon",
		category: "Bathroom Accessories",
		price: 19.99,
		countInStock: 11,
		rating: 5,
		numReviews: 12,
	},
	{
		_id: "5",
		name: "Unicorn Fluffly-Extra Fluff Bag",
		image: "/images/unicorn-fuffly-extra-fuff-aag.jpg",
		description:
			"Start the school year off right with the perfectf fluffy backpack! Featuring a rainbow design of pastel colours and sequins with a sparkly unicorn horn and ears, carry all your classroom essentials in this magical backpack.",
		brand: "Receesoon",
		category: "Stationery",
		price: 49.99,
		countInStock: 7,
		rating: 3.5,
		numReviews: 10,
	},
	{
		_id: "6",
		name: "Unicorn Double Fluffly Slippers",
		image: "/images/unicorn-double-fuffly-slippers.jpg",
		description:
			"EXTREMELY COMFORTABLE-Warm and comfy, the front sole cushion offers your foot with extra comfort while keeping them warm in case of cold weather.",
		brand: "Amazon",
		category: "Bedroom Accessories",
		price: 29.99,
		countInStock: 0,
		rating: 4,
		numReviews: 12,
	},
];

export default products;
